name: gtf-kgqa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - neo4j
      - PyYAML
      - requests
      - pandas
      - numpy
      - faiss-cpu
      - sentence-transformers
      - streamlit
      - pyvis
      - openpyxl
